In [40]:
import pandas as pd
import numpy as np
import os
import seaborn as sns

from sklearn.utils import resample
import imblearn
from imblearn.under_sampling import RandomUnderSampler
undersample = RandomUnderSampler(sampling_strategy=0.5)

In [41]:
#Data folder
d_path=os.path.join(os.getcwd(),"data")

In [45]:
df=pd.read_csv(d_path+"/input_training_data.csv")

In [54]:
df.head()

,ID,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,8568,0,0.0,0,0.0,2,0.000000,0.2,0.200000,0.0,0.0,Aug,1,1,3,1,Returning_Visitor,0,0
1,9207,1,5.0,0,0.0,2,15.200000,0.0,0.040000,0.0,0.0,Aug,1,1,6,3,Returning_Visitor,0,0
2,9321,0,0.0,0,0.0,3,0.000000,0.2,0.200000,0.0,0.0,Aug,1,1,3,4,Returning_Visitor,0,0
3,8955,4,54.8,0,0.0,3,20.257143,0.0,0.028571,0.0,0.0,Aug,1,1,3,2,Returning_Visitor,0,0
4,8180,0,0.0,0,0.0,4,39.800000,0.0,0.050000,0.0,0.0,Aug,1,1,1,3,New_Visitor,0,0

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8622 entries, 0 to 8621
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       8622 non-null   int64
 1   Administrative           8622 non-null   int64
 2   Administrative_Duration  8622 non-null   float64
 3   Informational            8622 non-null   int64
 4   Informational_Duration   8622 non-null   float64
 5   ProductRelated           8622 non-null   int64
 6   ProductRelated_Duration  8622 non-null   float64
 7   BounceRates              8622 non-null   float64
 8   ExitRates                8622 non-null   float64
 9   PageValues               8622 non-null   float64
 10  SpecialDay               8622 non-null   float64
 11  Month                    8622 non-null   object
 12  OperatingSystems         8622 non-null   int64
 13  Browser                  8622 non-null   int64
 14  Region                   8622 non-null   int64
 15  TrafficType              8622 non-null   int64
 16  VisitorType              8622 non-null   object
 17  Weekend                  8622 non-null   int64
 18  Revenue                  8622 non-null   int64
dtypes: float64(7), int64(10), object(2)
memory usage: 1.2+ MB

In [55]:
df.describe()

,ID,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,OperatingSystems,Browser,Region,TrafficType,Weekend,Revenue
count,8622.000000,8622.000000,8622.000000,8622.000000,8622.000000,8622.000000,8622.000000,8622.000000,8622.000000,8622.000000,8622.000000,8622.000000,8622.000000,8622.000000,8622.000000,8622.000000,8622.000000
mean,8015.889121,2.343192,83.405240,0.490373,33.159578,31.872419,1192.184366,0.021920,0.042457,5.704339,0.061795,2.124101,2.349803,3.154605,4.117606,0.233820,0.154836
std,2491.319819,3.315094,182.985925,1.258803,138.432097,44.605549,1944.264408,0.047651,0.047784,17.776590,0.199441,0.914461,1.719077,2.409020,4.070923,0.423284,0.361770
min,3701.000000,0.000000,-1.000000,0.000000,-1.000000,0.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,5859.250000,0.000000,0.000000,0.000000,0.000000,7.000000,192.462500,0.000000,0.014286,0.000000,0.000000,2.000000,2.000000,1.000000,2.000000,0.000000,0.000000
50%,8016.500000,1.000000,9.000000,0.000000,0.000000,18.000000,606.283333,0.003279,0.025000,0.000000,0.000000,2.000000,2.000000,3.000000,2.000000,0.000000,0.000000
75%,10172.750000,4.000000,95.575000,0.000000,0.000000,37.000000,1450.841355,0.017497,0.050000,0.000000,0.000000,3.000000,2.000000,4.000000,4.000000,0.000000,0.000000
max,12330.000000,26.000000,3398.750000,24.000000,2549.375000,705.000000,63973.522230,0.200000,0.200000,360.953384,1.000000,8.000000,13.000000,9.000000,20.000000,1.000000,1.000000

CAT vs NUM

In [49]:
#Define Catergorical and Numerical Columns
categorical_features = ['Month', 'VisitorType','OperatingSystems', 'Browser', 'Region', 'TrafficType', 'Weekend', 'Revenue']
numerical_features = ['Administrative', 'Administrative_Duration', 'Informational', 'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration', 'BounceRates', 'ExitRates', 'PageValues', 'SpecialDay']

#printing results
print("We have {} categorical features : {}".format(len(categorical_features),categorical_features))
print("We have {} numerical features : {}".format(len(numerical_features),numerical_features))

We have 8 categorical features : ['Month', 'VisitorType', 'OperatingSystems', 'Browser', 'Region', 'TrafficType', 'Weekend', 'Revenue']
We have 10 numerical features : ['Administrative', 'Administrative_Duration', 'Informational', 'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration', 'BounceRates', 'ExitRates', 'PageValues', 'SpecialDay']

#### Preparing X and Y variables

In [56]:
X= df.drop("Revenue",axis=1)

In [57]:
X.head()

,ID,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend
0,8568,0,0.0,0,0.0,2,0.000000,0.2,0.200000,0.0,0.0,Aug,1,1,3,1,Returning_Visitor,0
1,9207,1,5.0,0,0.0,2,15.200000,0.0,0.040000,0.0,0.0,Aug,1,1,6,3,Returning_Visitor,0
2,9321,0,0.0,0,0.0,3,0.000000,0.2,0.200000,0.0,0.0,Aug,1,1,3,4,Returning_Visitor,0
3,8955,4,54.8,0,0.0,3,20.257143,0.0,0.028571,0.0,0.0,Aug,1,1,3,2,Returning_Visitor,0
4,8180,0,0.0,0,0.0,4,39.800000,0.0,0.050000,0.0,0.0,Aug,1,1,1,3,New_Visitor,0

In [58]:
X.shape

(8622, 18)

In [59]:
y = df['Revenue']

In [60]:
y

0       0
1       0
2       0
3       0
4       0
       ..
8617    1
8618    1
8619    1
8620    1
8621    1
Name: Revenue, Length: 8622, dtype: int64

In [24]:
y.shape

(8622,)

### UNDER SAMPLING

In [61]:
x_under, y_under = undersample.fit_resample(X, y)

In [64]:
x_under.shape, y_under.shape

((4005, 18), (4005,))

In [63]:
from collections import Counter

print('Resampled dataset shape %s' % Counter(y_under))

Resampled dataset shape Counter({0: 2670, 1: 1335})

In [65]:
print("Categories in 'Month' variable:     ",end=" " )
print(X['Month'].unique())

print("Categories in 'OperatingSystems' variable:  ",end=" ")
print(X['OperatingSystems'].unique())

print("Categories in'Browser' variable:",end=" " )
print(X['Browser'].unique())

print("Categories in 'Region' variable:     ",end=" " )
print(X['Region'].unique())

print("Categories in 'TrafficType' variable:     ",end=" " )
print(X['TrafficType'].unique())

print("Categories in 'VisitorType' variable:     ",end=" " )
print(X['VisitorType'].unique())

print("Categories in 'Weekend' variable:     ",end=" " )
print(X['Weekend'].unique())

Categories in 'Month' variable:      ['Aug' 'Dec' 'Feb' 'Jul' 'June' 'Mar' 'May' 'Nov' 'Oct' 'Sep']
Categories in 'OperatingSystems' variable:   [1 2 3 4 5 6 7 8]
Categories in'Browser' variable: [ 1  8  2  6 13 10  5  4  7  3 12 11]
Categories in 'Region' variable:      [3 6 1 4 7 2 9 8 5]
Categories in 'TrafficType' variable:      [ 1  3  4  2  5  6 10 20  8 11  9 15 13 19  7 14 18 16 17]
Categories in 'VisitorType' variable:      ['Returning_Visitor' 'New_Visitor' 'Other']
Categories in 'Weekend' variable:      [0 1]

In [66]:
# Create Column Transfer with 3 types of transformers
categorical_features = ['Month', 'VisitorType','OperatingSystems', 'Browser', 'Region', 'TrafficType', 'Weekend']
numerical_features = ['Administrative', 'Administrative_Duration', 'Informational', 'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration', 'BounceRates', 'ExitRates', 'PageValues', 'SpecialDay']

num_features = X[numerical_features].columns
cat_features = X[categorical_features].columns

from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
oh_tranformer = OneHotEncoder()

preprocessor = ColumnTransformer(
    [
    ("OneHotEncoder",oh_tranformer,cat_features),
    ("StandardScaler",numeric_transformer,num_features)
    ]
)

In [68]:
x_under_ = preprocessor.fit_transform(x_under)

In [76]:
x_under_.shape

(4005, 71)

In [77]:
y_under.shape

(4005,)

In [81]:
from sklearn.model_selection import train_test_split

X_train,X_val,y_train,y_val = train_test_split(x_under_,y_under,test_size=0.2,random_state=42,shuffle=True)
X_train.shape, X_val.shape

((3204, 71), (801, 71))

#### Create an Evaluate Function to give all metrics after model Training

In [82]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score,roc_auc_score

In [83]:
def evaluate_model(true,predicted):
    accuracy = accuracy_score(true, predicted)
    precision = precision_score(true, predicted, average='macro')
    recall = recall_score(true, predicted, average='macro')
    f1 = f1_score(true, predicted, average='macro')
    roc_auc = roc_auc_score(true, predicted, average='macro', multi_class='ovo')
    return accuracy, precision, recall, f1, roc_auc

In [84]:
#Model Imports
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import AdaBoostClassifier
from catboost import CatBoostClassifier

#hyperparameter
from hyperopt import STATUS_OK, Trials, fmin, hp, tpe

In [85]:
models = {
    "Logistic Regression": LogisticRegression(),
    "K-Neighbors Classifier": KNeighborsClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest Classifier": RandomForestClassifier(),
    "Support Vector Machine": SVC(),
    "Naive Bayes": GaussianNB(),
    "Gradient Boosting":GradientBoostingClassifier(),
    "XGBoost Classifier":XGBClassifier(),
    "AdaBoost Classifier": AdaBoostClassifier(),
    "CatBoost Classifier": CatBoostClassifier()
}

In [86]:
model_list =[]
roc_auc_list=[]

for i in range(len(list(models))):
    model =list(models.values())[i]
    model.fit(X_train,y_train) # Train model

    #Make predictions
    y_train_pred = model.predict(X_train)
    y_val_pred = model.predict(X_val)

    #Evaluate Train and Val dataset
    model_train_accuracy, model_train_precision, model_train_recall, model_train_f1, model_train_roc_auc = evaluate_model(y_train,y_train_pred)

    model_val_accuracy, model_val_precision, model_val_recall, model_val_f1, model_val_roc_auc = evaluate_model(y_val,y_val_pred)
    
    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])


    print('----------------------------------')
    print('Model performance for Training set')
    print("- Accuracy: {:.4f}".format(model_train_accuracy))
    print("- Precision: {:.4f}".format(model_train_precision))
    print("- Recall: {:.4f}".format(model_train_recall))
    print("- F1 Score: {:.4f}".format(model_train_f1))
    print("- ROC AUC Score: {:.4f}".format(model_train_roc_auc))
    print('----------------------------------')

    print('----------------------------------')
    print('Model performance for Training set')
    print("- Accuracy: {:.4f}".format(model_val_accuracy))
    print("- Precision: {:.4f}".format(model_val_precision))
    print("- Recall: {:.4f}".format(model_val_recall))
    print("- F1 Score: {:.4f}".format(model_val_f1))
    print("- ROC AUC Score: {:.4f}".format(model_val_roc_auc))
    print('----------------------------------')
    roc_auc_list.append(model_val_roc_auc)
    print('='*35)
    print('\n')

c:\Users\SkyLake\.conda\envs\proj02\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Logistic Regression
----------------------------------
Model performance for Training set
- Accuracy: 0.8280
- Precision: 0.8295
- Recall: 0.7785
- F1 Score: 0.7947
- ROC AUC Score: 0.7785
----------------------------------
----------------------------------
Model performance for Training set
- Accuracy: 0.8439
- Precision: 0.8411
- Recall: 0.7730
- F1 Score: 0.7955
- ROC AUC Score: 0.7730
----------------------------------
===================================


K-Neighbors Classifier
----------------------------------
Model performance for Training set
- Accuracy: 0.8427
- Precision: 0.8364
- Recall: 0.8059
- F1 Score: 0.8175
- ROC AUC Score: 0.8059
----------------------------------
----------------------------------
Model performance for Training set
- Accuracy: 0.7890
- Precision: 0.7540
- Recall: 0.7182
- F1 Score: 0.7310
- ROC AUC Score: 0.7182
----------------------------------
===================================


Decision Tree
----------------------------------
Model performance for Training set
- Accuracy: 1.0000
- Precision: 1.0000
- Recall: 1.0000
- F1 Score: 1.0000
- ROC AUC Score: 1.0000
----------------------------------
----------------------------------
Model performance for Training set
- Accuracy: 0.8265
- Precision: 0.7944
- Recall: 0.7879
- F1 Score: 0.7910
- ROC AUC Score: 0.7879
----------------------------------
===================================


Random Forest Classifier
----------------------------------
Model performance for Training set
- Accuracy: 1.0000
- Precision: 1.0000
- Recall: 1.0000
- F1 Score: 1.0000
- ROC AUC Score: 1.0000
----------------------------------
----------------------------------
Model performance for Training set
- Accuracy: 0.8552
- Precision: 0.8324
- Recall: 0.8156
- F1 Score: 0.8231
- ROC AUC Score: 0.8156
----------------------------------
===================================


Support Vector Machine
----------------------------------
Model performance for Training set
- Accuracy: 0.8645
- Precision: 0.8665
- Recall: 0.8271
- F1 Score: 0.8417
- ROC AUC Score: 0.8271
----------------------------------
----------------------------------
Model performance for Training set
- Accuracy: 0.8477
- Precision: 0.8371
- Recall: 0.7864
- F1 Score: 0.8049
- ROC AUC Score: 0.7864
----------------------------------
===================================

TypeError: A sparse matrix was passed, but dense data is required. Use X.toarray() to convert to a dense numpy array.